name: 'Setup Build Environment'
description: 'Sets up the build environment'
runs:
  using: composite
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
