name: "Setup"
description: "Sets up the build environment"
runs:
  using: composite
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y cmake build-essential
