name: 'Run Benchmarks'
description: 'Runs all benchmark executables'
runs:
  using: composite
  steps:
    - name: Run Benchmarks
      shell: bash
      run: |
        cd build/benchmarks && for benchmark in benchmark_*; do
          if [ -x "$benchmark" ]; then
            ./$benchmark
          fi
        done
