#ifndef __DSC_ERROR_H__
#define __DSC_ERROR_H__

enum dsc_error_t {
    ERROR_NONE,
    ERROR_INVALID_ARGUMENT,
    ERROR_OUT_OF_MEMORY,
    ERROR_EMPTY_LIST,
    ERROR_INDEX_OUT_OF_BOUNDS,
    ERROR_VALUE_NOT_FOUND
};

#endif // __DSC_ERROR_H__
