name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: {}
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/build
      - uses: ./.github/actions/run-tests
      - uses: ./.github/actions/coverage
      - uses: ./.github/actions/run-benchmarks
