name: Create a new release
on:
  push:
    tags: ['v*.*.*']
permissions:
  contents: write
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/build
        with:
          build_type: Release
      - id: tests
        uses: ./.github/actions/run-tests

      - if: steps.tests.outputs.passed == 'true'
        name: Create source archive
        run: |
          tar czf libdsc-${{ github.ref_name }}.tar.gz \
            build/libdsc.* \
            include/libdsc

      - if: steps.tests.outputs.passed == 'true'
        id: debian-package
        uses: ./.github/actions/package
        with:
          distribution: debian
          version: ${{ github.ref_name }}

      - if: steps.tests.outputs.passed == 'true'
        id: rpm-package
        uses: ./.github/actions/package
        with:
          distribution: rpm
          version: ${{ github.ref_name }}

      - if: steps.tests.outputs.passed == 'true'
        id: arch-package
        uses: ./.github/actions/package
        with:
          distribution: arch
          version: ${{ github.ref_name }}

      - if: steps.tests.outputs.passed == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            libdsc-${{ github.ref_name }}.tar.gz
            ${{ steps.debian-package.outputs.package-path }}
            ${{ steps.rpm-package.outputs.package-path }}
            ${{ steps.arch-package.outputs.package-path }}
          generate_release_notes: true
